version: 2.1

#orbs:
#  maven: circleci/maven@1.0.1

jobs:
#  build:
#    - maven/test # checkout, build, test, and upload test results
  test-postgres:
    working_directory: ~/failsafe-executor
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: failsafe
          POSTGRES_PASSWORD: failsafe
          POSTGRES_DB: failsafe
    environment:
      TEST_DB: POSTGRES
    steps:
      - checkout
      - restore_cache:
          key: failsafe-executor-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: failsafe-executor-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build_and_test:
    jobs:
#      - build
      - test-postgres
